apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
  name: fluent-bit
  namespace: default
spec:
  # fluentBitConfigName: fluent-bit-config
  fluentBitConfigName: clusterfluentbitconfig-system-config
  image: kubesphere/fluent-bit:v2.2.2
  # namespaceFluentBitCfgSelector: {}
  namespaceFluentBitCfgSelector:
    matchLabels:
      fluent-bit: system
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  resources: {}
  service: {}
status: {}
