apiVersion: fluentbit.fluent.io/v1alpha2
kind: Output
metadata:
  name: output-stdout-user
  namespace: fluent
  labels:
    fluentbit.fluent.io/enabled: "user"
spec:
  match: '*'
  stdout:
    format: json

