apiVersion: fluentbit.fluent.io/v1alpha2
kind: Output
metadata:
  name: output-loki-user1
  namespace: fluent
  labels:
    fluentbit.fluent.io/enabled: "user"
spec:
  match: '*'
  loki:
    autoKubernetesLabels: "on"
    host: 192.168.2.203
    port: 3100
    labels:
      - job=sokoide

